version: "3.2"
services:
  instr-api:
    image: instr-container
    container_name: instr-app
    environment:
      - NODE_ENV=production
      - PORT=5000
      - REDIS_URL=redis://cache:6379
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
     - cache  
  cache:
    image: redis:latest
    container_name: cache
